// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Operation.proto

#include "Operation.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace OperationsTool {
PROTOBUF_CONSTEXPR Claim::Claim(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.auth_code_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.platform_guid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.made_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.nickname_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.join_date_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.platform_type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ClaimDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClaimDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClaimDefaultTypeInternal() {}
  union {
    Claim _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClaimDefaultTypeInternal _Claim_default_instance_;
PROTOBUF_CONSTEXPR OperationReq_Property::OperationReq_Property(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.property_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct OperationReq_PropertyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OperationReq_PropertyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OperationReq_PropertyDefaultTypeInternal() {}
  union {
    OperationReq_Property _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OperationReq_PropertyDefaultTypeInternal _OperationReq_Property_default_instance_;
PROTOBUF_CONSTEXPR OperationReq_Avatar::OperationReq_Avatar(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.expiry_date_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OperationReq_AvatarDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OperationReq_AvatarDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OperationReq_AvatarDefaultTypeInternal() {}
  union {
    OperationReq_Avatar _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OperationReq_AvatarDefaultTypeInternal _OperationReq_Avatar_default_instance_;
PROTOBUF_CONSTEXPR OperationReq_Quest::OperationReq_Quest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.current_count_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OperationReq_QuestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OperationReq_QuestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OperationReq_QuestDefaultTypeInternal() {}
  union {
    OperationReq_Quest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OperationReq_QuestDefaultTypeInternal _OperationReq_Quest_default_instance_;
PROTOBUF_CONSTEXPR OperationReq_Mailbox::OperationReq_Mailbox(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.mail_idx_)*/{}
  , /*decltype(_impl_._mail_idx_cached_byte_size_)*/{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OperationReq_MailboxDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OperationReq_MailboxDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OperationReq_MailboxDefaultTypeInternal() {}
  union {
    OperationReq_Mailbox _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OperationReq_MailboxDefaultTypeInternal _OperationReq_Mailbox_default_instance_;
PROTOBUF_CONSTEXPR OperationReq::OperationReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.reason_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.before_)*/nullptr
  , /*decltype(_impl_.after_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OperationReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OperationReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OperationReqDefaultTypeInternal() {}
  union {
    OperationReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OperationReqDefaultTypeInternal _OperationReq_default_instance_;
}  // namespace OperationsTool
static ::_pb::Metadata file_level_metadata_Operation_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Operation_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Operation_2eproto = nullptr;

const uint32_t TableStruct_Operation_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::OperationsTool::Claim, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::OperationsTool::Claim, _impl_.auth_code_),
  PROTOBUF_FIELD_OFFSET(::OperationsTool::Claim, _impl_.platform_guid_),
  PROTOBUF_FIELD_OFFSET(::OperationsTool::Claim, _impl_.made_id_),
  PROTOBUF_FIELD_OFFSET(::OperationsTool::Claim, _impl_.nickname_),
  PROTOBUF_FIELD_OFFSET(::OperationsTool::Claim, _impl_.platform_type_),
  PROTOBUF_FIELD_OFFSET(::OperationsTool::Claim, _impl_.join_date_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::OperationsTool::OperationReq_Property, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::OperationsTool::OperationReq_Property, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::OperationsTool::OperationReq_Property, _impl_.property_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::OperationsTool::OperationReq_Avatar, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::OperationsTool::OperationReq_Avatar, _impl_.expiry_date_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::OperationsTool::OperationReq_Quest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::OperationsTool::OperationReq_Quest, _impl_.current_count_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::OperationsTool::OperationReq_Mailbox, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::OperationsTool::OperationReq_Mailbox, _impl_.mail_idx_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::OperationsTool::OperationReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::OperationsTool::OperationReq, _impl_.before_),
  PROTOBUF_FIELD_OFFSET(::OperationsTool::OperationReq, _impl_.after_),
  PROTOBUF_FIELD_OFFSET(::OperationsTool::OperationReq, _impl_.reason_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::OperationsTool::Claim)},
  { 12, -1, -1, sizeof(::OperationsTool::OperationReq_Property)},
  { 40, -1, -1, sizeof(::OperationsTool::OperationReq_Avatar)},
  { 47, -1, -1, sizeof(::OperationsTool::OperationReq_Quest)},
  { 54, -1, -1, sizeof(::OperationsTool::OperationReq_Mailbox)},
  { 61, -1, -1, sizeof(::OperationsTool::OperationReq)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::OperationsTool::_Claim_default_instance_._instance,
  &::OperationsTool::_OperationReq_Property_default_instance_._instance,
  &::OperationsTool::_OperationReq_Avatar_default_instance_._instance,
  &::OperationsTool::_OperationReq_Quest_default_instance_._instance,
  &::OperationsTool::_OperationReq_Mailbox_default_instance_._instance,
  &::OperationsTool::_OperationReq_default_instance_._instance,
};

const char descriptor_table_protodef_Operation_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017Operation.proto\022\016OperationsTool\032\rGener"
  "al.proto\032\013PmNet.proto\032\014Server.proto\032\017tim"
  "estamp.proto\032\016wrappers.proto\"\232\001\n\005Claim\022\021"
  "\n\tauth_code\030\001 \001(\t\022\025\n\rplatform_guid\030\002 \001(\t"
  "\022\017\n\007made_id\030\003 \001(\t\022\020\n\010nickname\030\004 \001(\t\0221\n\rp"
  "latform_type\030\005 \001(\0162\032.General.AccessChann"
  "elType\022\021\n\tjoin_date\030\006 \001(\t\"\316\006\n\014OperationR"
  "eq\0225\n\006before\030\001 \001(\0132%.OperationsTool.Oper"
  "ationReq.Property\0224\n\005after\030\002 \001(\0132%.Opera"
  "tionsTool.OperationReq.Property\022\016\n\006reaso"
  "n\030\003 \001(\t\032\344\004\n\010Property\022\022\n\010nickname\030\001 \001(\tH\000"
  "\022\r\n\003exp\030\002 \001(\003H\000\022\r\n\003gem\030\003 \001(\003H\000\022\022\n\010paid_g"
  "em\030\004 \001(\003H\000\022\017\n\005chips\030\005 \001(\003H\000\022\016\n\004coin\030\006 \001("
  "\003H\000\022\024\n\nsafe_chips\030\007 \001(\003H\000\022\023\n\tsafe_coin\030\010"
  " \001(\003H\000\022\022\n\010rakeback\030\t \001(\003H\000\022\033\n\021kick_ticke"
  "t_count\030\n \001(\005H\000\022 \n\026membership_expiry_tim"
  "e\030\013 \001(\tH\000\022\031\n\017daily_lost_chip\030\025 \001(\003H\000\022\024\n\n"
  "lost_limit\030\026 \001(\003H\000\022$\n\032refresh_time_of_lo"
  "ss_limit\030\027 \001(\tH\000\022\033\n\021monthly_buy_total\030\030 "
  "\001(\003H\000\022\023\n\tbuy_limit\030\031 \001(\003H\000\022#\n\031refresh_ti"
  "me_of_buy_limit\030\032 \001(\tH\000\022\022\n\010reg_date\030\037 \001("
  "\tH\000\0226\n\007avatars\030) \001(\0132#.OperationsTool.Op"
  "erationReq.AvatarH\000\0224\n\006quests\0303 \001(\0132\".Op"
  "erationsTool.OperationReq.QuestH\000\0227\n\007mai"
  "lbox\030= \001(\0132$.OperationsTool.OperationReq"
  ".MailboxH\000B\n\n\010property\032\035\n\006Avatar\022\023\n\013expi"
  "ry_date\030) \001(\t\032\036\n\005Quest\022\025\n\rcurrent_count\030"
  "3 \001(\003\032\033\n\007Mailbox\022\020\n\010mail_idx\030= \003(\003b\006prot"
  "o3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Operation_2eproto_deps[5] = {
  &::descriptor_table_General_2eproto,
  &::descriptor_table_PmNet_2eproto,
  &::descriptor_table_Server_2eproto,
  &::descriptor_table_timestamp_2eproto,
  &::descriptor_table_wrappers_2eproto,
};
static ::_pbi::once_flag descriptor_table_Operation_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Operation_2eproto = {
    false, false, 1122, descriptor_table_protodef_Operation_2eproto,
    "Operation.proto",
    &descriptor_table_Operation_2eproto_once, descriptor_table_Operation_2eproto_deps, 5, 6,
    schemas, file_default_instances, TableStruct_Operation_2eproto::offsets,
    file_level_metadata_Operation_2eproto, file_level_enum_descriptors_Operation_2eproto,
    file_level_service_descriptors_Operation_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Operation_2eproto_getter() {
  return &descriptor_table_Operation_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Operation_2eproto(&descriptor_table_Operation_2eproto);
namespace OperationsTool {

// ===================================================================

class Claim::_Internal {
 public:
};

Claim::Claim(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:OperationsTool.Claim)
}
Claim::Claim(const Claim& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Claim* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.auth_code_){}
    , decltype(_impl_.platform_guid_){}
    , decltype(_impl_.made_id_){}
    , decltype(_impl_.nickname_){}
    , decltype(_impl_.join_date_){}
    , decltype(_impl_.platform_type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.auth_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.auth_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_auth_code().empty()) {
    _this->_impl_.auth_code_.Set(from._internal_auth_code(), 
      _this->GetArenaForAllocation());
  }
  _impl_.platform_guid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.platform_guid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_platform_guid().empty()) {
    _this->_impl_.platform_guid_.Set(from._internal_platform_guid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.made_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.made_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_made_id().empty()) {
    _this->_impl_.made_id_.Set(from._internal_made_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.nickname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nickname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_nickname().empty()) {
    _this->_impl_.nickname_.Set(from._internal_nickname(), 
      _this->GetArenaForAllocation());
  }
  _impl_.join_date_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.join_date_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_join_date().empty()) {
    _this->_impl_.join_date_.Set(from._internal_join_date(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.platform_type_ = from._impl_.platform_type_;
  // @@protoc_insertion_point(copy_constructor:OperationsTool.Claim)
}

inline void Claim::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.auth_code_){}
    , decltype(_impl_.platform_guid_){}
    , decltype(_impl_.made_id_){}
    , decltype(_impl_.nickname_){}
    , decltype(_impl_.join_date_){}
    , decltype(_impl_.platform_type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.auth_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.auth_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.platform_guid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.platform_guid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.made_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.made_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.nickname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nickname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.join_date_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.join_date_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Claim::~Claim() {
  // @@protoc_insertion_point(destructor:OperationsTool.Claim)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Claim::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.auth_code_.Destroy();
  _impl_.platform_guid_.Destroy();
  _impl_.made_id_.Destroy();
  _impl_.nickname_.Destroy();
  _impl_.join_date_.Destroy();
}

void Claim::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Claim::Clear() {
// @@protoc_insertion_point(message_clear_start:OperationsTool.Claim)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.auth_code_.ClearToEmpty();
  _impl_.platform_guid_.ClearToEmpty();
  _impl_.made_id_.ClearToEmpty();
  _impl_.nickname_.ClearToEmpty();
  _impl_.join_date_.ClearToEmpty();
  _impl_.platform_type_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Claim::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string auth_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_auth_code();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "OperationsTool.Claim.auth_code"));
        } else
          goto handle_unusual;
        continue;
      // string platform_guid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_platform_guid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "OperationsTool.Claim.platform_guid"));
        } else
          goto handle_unusual;
        continue;
      // string made_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_made_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "OperationsTool.Claim.made_id"));
        } else
          goto handle_unusual;
        continue;
      // string nickname = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_nickname();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "OperationsTool.Claim.nickname"));
        } else
          goto handle_unusual;
        continue;
      // .General.AccessChannelType platform_type = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_platform_type(static_cast<::General::AccessChannelType>(val));
        } else
          goto handle_unusual;
        continue;
      // string join_date = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_join_date();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "OperationsTool.Claim.join_date"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Claim::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:OperationsTool.Claim)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string auth_code = 1;
  if (!this->_internal_auth_code().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_auth_code().data(), static_cast<int>(this->_internal_auth_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "OperationsTool.Claim.auth_code");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_auth_code(), target);
  }

  // string platform_guid = 2;
  if (!this->_internal_platform_guid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_platform_guid().data(), static_cast<int>(this->_internal_platform_guid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "OperationsTool.Claim.platform_guid");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_platform_guid(), target);
  }

  // string made_id = 3;
  if (!this->_internal_made_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_made_id().data(), static_cast<int>(this->_internal_made_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "OperationsTool.Claim.made_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_made_id(), target);
  }

  // string nickname = 4;
  if (!this->_internal_nickname().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_nickname().data(), static_cast<int>(this->_internal_nickname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "OperationsTool.Claim.nickname");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_nickname(), target);
  }

  // .General.AccessChannelType platform_type = 5;
  if (this->_internal_platform_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      5, this->_internal_platform_type(), target);
  }

  // string join_date = 6;
  if (!this->_internal_join_date().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_join_date().data(), static_cast<int>(this->_internal_join_date().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "OperationsTool.Claim.join_date");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_join_date(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OperationsTool.Claim)
  return target;
}

size_t Claim::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OperationsTool.Claim)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string auth_code = 1;
  if (!this->_internal_auth_code().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_auth_code());
  }

  // string platform_guid = 2;
  if (!this->_internal_platform_guid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_platform_guid());
  }

  // string made_id = 3;
  if (!this->_internal_made_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_made_id());
  }

  // string nickname = 4;
  if (!this->_internal_nickname().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_nickname());
  }

  // string join_date = 6;
  if (!this->_internal_join_date().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_join_date());
  }

  // .General.AccessChannelType platform_type = 5;
  if (this->_internal_platform_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_platform_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Claim::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Claim::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Claim::GetClassData() const { return &_class_data_; }


void Claim::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Claim*>(&to_msg);
  auto& from = static_cast<const Claim&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:OperationsTool.Claim)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_auth_code().empty()) {
    _this->_internal_set_auth_code(from._internal_auth_code());
  }
  if (!from._internal_platform_guid().empty()) {
    _this->_internal_set_platform_guid(from._internal_platform_guid());
  }
  if (!from._internal_made_id().empty()) {
    _this->_internal_set_made_id(from._internal_made_id());
  }
  if (!from._internal_nickname().empty()) {
    _this->_internal_set_nickname(from._internal_nickname());
  }
  if (!from._internal_join_date().empty()) {
    _this->_internal_set_join_date(from._internal_join_date());
  }
  if (from._internal_platform_type() != 0) {
    _this->_internal_set_platform_type(from._internal_platform_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Claim::CopyFrom(const Claim& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OperationsTool.Claim)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Claim::IsInitialized() const {
  return true;
}

void Claim::InternalSwap(Claim* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.auth_code_, lhs_arena,
      &other->_impl_.auth_code_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.platform_guid_, lhs_arena,
      &other->_impl_.platform_guid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.made_id_, lhs_arena,
      &other->_impl_.made_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.nickname_, lhs_arena,
      &other->_impl_.nickname_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.join_date_, lhs_arena,
      &other->_impl_.join_date_, rhs_arena
  );
  swap(_impl_.platform_type_, other->_impl_.platform_type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Claim::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Operation_2eproto_getter, &descriptor_table_Operation_2eproto_once,
      file_level_metadata_Operation_2eproto[0]);
}

// ===================================================================

class OperationReq_Property::_Internal {
 public:
  static const ::OperationsTool::OperationReq_Avatar& avatars(const OperationReq_Property* msg);
  static const ::OperationsTool::OperationReq_Quest& quests(const OperationReq_Property* msg);
  static const ::OperationsTool::OperationReq_Mailbox& mailbox(const OperationReq_Property* msg);
};

const ::OperationsTool::OperationReq_Avatar&
OperationReq_Property::_Internal::avatars(const OperationReq_Property* msg) {
  return *msg->_impl_.property_.avatars_;
}
const ::OperationsTool::OperationReq_Quest&
OperationReq_Property::_Internal::quests(const OperationReq_Property* msg) {
  return *msg->_impl_.property_.quests_;
}
const ::OperationsTool::OperationReq_Mailbox&
OperationReq_Property::_Internal::mailbox(const OperationReq_Property* msg) {
  return *msg->_impl_.property_.mailbox_;
}
void OperationReq_Property::set_allocated_avatars(::OperationsTool::OperationReq_Avatar* avatars) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_property();
  if (avatars) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(avatars);
    if (message_arena != submessage_arena) {
      avatars = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, avatars, submessage_arena);
    }
    set_has_avatars();
    _impl_.property_.avatars_ = avatars;
  }
  // @@protoc_insertion_point(field_set_allocated:OperationsTool.OperationReq.Property.avatars)
}
void OperationReq_Property::set_allocated_quests(::OperationsTool::OperationReq_Quest* quests) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_property();
  if (quests) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(quests);
    if (message_arena != submessage_arena) {
      quests = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, quests, submessage_arena);
    }
    set_has_quests();
    _impl_.property_.quests_ = quests;
  }
  // @@protoc_insertion_point(field_set_allocated:OperationsTool.OperationReq.Property.quests)
}
void OperationReq_Property::set_allocated_mailbox(::OperationsTool::OperationReq_Mailbox* mailbox) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_property();
  if (mailbox) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(mailbox);
    if (message_arena != submessage_arena) {
      mailbox = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, mailbox, submessage_arena);
    }
    set_has_mailbox();
    _impl_.property_.mailbox_ = mailbox;
  }
  // @@protoc_insertion_point(field_set_allocated:OperationsTool.OperationReq.Property.mailbox)
}
OperationReq_Property::OperationReq_Property(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:OperationsTool.OperationReq.Property)
}
OperationReq_Property::OperationReq_Property(const OperationReq_Property& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OperationReq_Property* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.property_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_property();
  switch (from.property_case()) {
    case kNickname: {
      _this->_internal_set_nickname(from._internal_nickname());
      break;
    }
    case kExp: {
      _this->_internal_set_exp(from._internal_exp());
      break;
    }
    case kGem: {
      _this->_internal_set_gem(from._internal_gem());
      break;
    }
    case kPaidGem: {
      _this->_internal_set_paid_gem(from._internal_paid_gem());
      break;
    }
    case kChips: {
      _this->_internal_set_chips(from._internal_chips());
      break;
    }
    case kCoin: {
      _this->_internal_set_coin(from._internal_coin());
      break;
    }
    case kSafeChips: {
      _this->_internal_set_safe_chips(from._internal_safe_chips());
      break;
    }
    case kSafeCoin: {
      _this->_internal_set_safe_coin(from._internal_safe_coin());
      break;
    }
    case kRakeback: {
      _this->_internal_set_rakeback(from._internal_rakeback());
      break;
    }
    case kKickTicketCount: {
      _this->_internal_set_kick_ticket_count(from._internal_kick_ticket_count());
      break;
    }
    case kMembershipExpiryTime: {
      _this->_internal_set_membership_expiry_time(from._internal_membership_expiry_time());
      break;
    }
    case kDailyLostChip: {
      _this->_internal_set_daily_lost_chip(from._internal_daily_lost_chip());
      break;
    }
    case kLostLimit: {
      _this->_internal_set_lost_limit(from._internal_lost_limit());
      break;
    }
    case kRefreshTimeOfLossLimit: {
      _this->_internal_set_refresh_time_of_loss_limit(from._internal_refresh_time_of_loss_limit());
      break;
    }
    case kMonthlyBuyTotal: {
      _this->_internal_set_monthly_buy_total(from._internal_monthly_buy_total());
      break;
    }
    case kBuyLimit: {
      _this->_internal_set_buy_limit(from._internal_buy_limit());
      break;
    }
    case kRefreshTimeOfBuyLimit: {
      _this->_internal_set_refresh_time_of_buy_limit(from._internal_refresh_time_of_buy_limit());
      break;
    }
    case kRegDate: {
      _this->_internal_set_reg_date(from._internal_reg_date());
      break;
    }
    case kAvatars: {
      _this->_internal_mutable_avatars()->::OperationsTool::OperationReq_Avatar::MergeFrom(
          from._internal_avatars());
      break;
    }
    case kQuests: {
      _this->_internal_mutable_quests()->::OperationsTool::OperationReq_Quest::MergeFrom(
          from._internal_quests());
      break;
    }
    case kMailbox: {
      _this->_internal_mutable_mailbox()->::OperationsTool::OperationReq_Mailbox::MergeFrom(
          from._internal_mailbox());
      break;
    }
    case PROPERTY_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:OperationsTool.OperationReq.Property)
}

inline void OperationReq_Property::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.property_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_property();
}

OperationReq_Property::~OperationReq_Property() {
  // @@protoc_insertion_point(destructor:OperationsTool.OperationReq.Property)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OperationReq_Property::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_property()) {
    clear_property();
  }
}

void OperationReq_Property::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OperationReq_Property::clear_property() {
// @@protoc_insertion_point(one_of_clear_start:OperationsTool.OperationReq.Property)
  switch (property_case()) {
    case kNickname: {
      _impl_.property_.nickname_.Destroy();
      break;
    }
    case kExp: {
      // No need to clear
      break;
    }
    case kGem: {
      // No need to clear
      break;
    }
    case kPaidGem: {
      // No need to clear
      break;
    }
    case kChips: {
      // No need to clear
      break;
    }
    case kCoin: {
      // No need to clear
      break;
    }
    case kSafeChips: {
      // No need to clear
      break;
    }
    case kSafeCoin: {
      // No need to clear
      break;
    }
    case kRakeback: {
      // No need to clear
      break;
    }
    case kKickTicketCount: {
      // No need to clear
      break;
    }
    case kMembershipExpiryTime: {
      _impl_.property_.membership_expiry_time_.Destroy();
      break;
    }
    case kDailyLostChip: {
      // No need to clear
      break;
    }
    case kLostLimit: {
      // No need to clear
      break;
    }
    case kRefreshTimeOfLossLimit: {
      _impl_.property_.refresh_time_of_loss_limit_.Destroy();
      break;
    }
    case kMonthlyBuyTotal: {
      // No need to clear
      break;
    }
    case kBuyLimit: {
      // No need to clear
      break;
    }
    case kRefreshTimeOfBuyLimit: {
      _impl_.property_.refresh_time_of_buy_limit_.Destroy();
      break;
    }
    case kRegDate: {
      _impl_.property_.reg_date_.Destroy();
      break;
    }
    case kAvatars: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.property_.avatars_;
      }
      break;
    }
    case kQuests: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.property_.quests_;
      }
      break;
    }
    case kMailbox: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.property_.mailbox_;
      }
      break;
    }
    case PROPERTY_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PROPERTY_NOT_SET;
}


void OperationReq_Property::Clear() {
// @@protoc_insertion_point(message_clear_start:OperationsTool.OperationReq.Property)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_property();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OperationReq_Property::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string nickname = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_nickname();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "OperationsTool.OperationReq.Property.nickname"));
        } else
          goto handle_unusual;
        continue;
      // int64 exp = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _internal_set_exp(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 gem = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _internal_set_gem(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 paid_gem = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _internal_set_paid_gem(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 chips = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _internal_set_chips(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 coin = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _internal_set_coin(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 safe_chips = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _internal_set_safe_chips(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 safe_coin = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _internal_set_safe_coin(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 rakeback = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _internal_set_rakeback(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 kick_ticket_count = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _internal_set_kick_ticket_count(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string membership_expiry_time = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_membership_expiry_time();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "OperationsTool.OperationReq.Property.membership_expiry_time"));
        } else
          goto handle_unusual;
        continue;
      // int64 daily_lost_chip = 21;
      case 21:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 168)) {
          _internal_set_daily_lost_chip(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 lost_limit = 22;
      case 22:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 176)) {
          _internal_set_lost_limit(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string refresh_time_of_loss_limit = 23;
      case 23:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 186)) {
          auto str = _internal_mutable_refresh_time_of_loss_limit();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "OperationsTool.OperationReq.Property.refresh_time_of_loss_limit"));
        } else
          goto handle_unusual;
        continue;
      // int64 monthly_buy_total = 24;
      case 24:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 192)) {
          _internal_set_monthly_buy_total(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 buy_limit = 25;
      case 25:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 200)) {
          _internal_set_buy_limit(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string refresh_time_of_buy_limit = 26;
      case 26:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 210)) {
          auto str = _internal_mutable_refresh_time_of_buy_limit();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "OperationsTool.OperationReq.Property.refresh_time_of_buy_limit"));
        } else
          goto handle_unusual;
        continue;
      // string reg_date = 31;
      case 31:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 250)) {
          auto str = _internal_mutable_reg_date();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "OperationsTool.OperationReq.Property.reg_date"));
        } else
          goto handle_unusual;
        continue;
      // .OperationsTool.OperationReq.Avatar avatars = 41;
      case 41:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_avatars(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .OperationsTool.OperationReq.Quest quests = 51;
      case 51:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 154)) {
          ptr = ctx->ParseMessage(_internal_mutable_quests(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .OperationsTool.OperationReq.Mailbox mailbox = 61;
      case 61:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 234)) {
          ptr = ctx->ParseMessage(_internal_mutable_mailbox(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OperationReq_Property::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:OperationsTool.OperationReq.Property)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string nickname = 1;
  if (_internal_has_nickname()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_nickname().data(), static_cast<int>(this->_internal_nickname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "OperationsTool.OperationReq.Property.nickname");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_nickname(), target);
  }

  // int64 exp = 2;
  if (_internal_has_exp()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_exp(), target);
  }

  // int64 gem = 3;
  if (_internal_has_gem()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_gem(), target);
  }

  // int64 paid_gem = 4;
  if (_internal_has_paid_gem()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_paid_gem(), target);
  }

  // int64 chips = 5;
  if (_internal_has_chips()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(5, this->_internal_chips(), target);
  }

  // int64 coin = 6;
  if (_internal_has_coin()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(6, this->_internal_coin(), target);
  }

  // int64 safe_chips = 7;
  if (_internal_has_safe_chips()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(7, this->_internal_safe_chips(), target);
  }

  // int64 safe_coin = 8;
  if (_internal_has_safe_coin()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(8, this->_internal_safe_coin(), target);
  }

  // int64 rakeback = 9;
  if (_internal_has_rakeback()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(9, this->_internal_rakeback(), target);
  }

  // int32 kick_ticket_count = 10;
  if (_internal_has_kick_ticket_count()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(10, this->_internal_kick_ticket_count(), target);
  }

  // string membership_expiry_time = 11;
  if (_internal_has_membership_expiry_time()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_membership_expiry_time().data(), static_cast<int>(this->_internal_membership_expiry_time().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "OperationsTool.OperationReq.Property.membership_expiry_time");
    target = stream->WriteStringMaybeAliased(
        11, this->_internal_membership_expiry_time(), target);
  }

  // int64 daily_lost_chip = 21;
  if (_internal_has_daily_lost_chip()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(21, this->_internal_daily_lost_chip(), target);
  }

  // int64 lost_limit = 22;
  if (_internal_has_lost_limit()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(22, this->_internal_lost_limit(), target);
  }

  // string refresh_time_of_loss_limit = 23;
  if (_internal_has_refresh_time_of_loss_limit()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_refresh_time_of_loss_limit().data(), static_cast<int>(this->_internal_refresh_time_of_loss_limit().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "OperationsTool.OperationReq.Property.refresh_time_of_loss_limit");
    target = stream->WriteStringMaybeAliased(
        23, this->_internal_refresh_time_of_loss_limit(), target);
  }

  // int64 monthly_buy_total = 24;
  if (_internal_has_monthly_buy_total()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(24, this->_internal_monthly_buy_total(), target);
  }

  // int64 buy_limit = 25;
  if (_internal_has_buy_limit()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(25, this->_internal_buy_limit(), target);
  }

  // string refresh_time_of_buy_limit = 26;
  if (_internal_has_refresh_time_of_buy_limit()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_refresh_time_of_buy_limit().data(), static_cast<int>(this->_internal_refresh_time_of_buy_limit().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "OperationsTool.OperationReq.Property.refresh_time_of_buy_limit");
    target = stream->WriteStringMaybeAliased(
        26, this->_internal_refresh_time_of_buy_limit(), target);
  }

  // string reg_date = 31;
  if (_internal_has_reg_date()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_reg_date().data(), static_cast<int>(this->_internal_reg_date().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "OperationsTool.OperationReq.Property.reg_date");
    target = stream->WriteStringMaybeAliased(
        31, this->_internal_reg_date(), target);
  }

  // .OperationsTool.OperationReq.Avatar avatars = 41;
  if (_internal_has_avatars()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(41, _Internal::avatars(this),
        _Internal::avatars(this).GetCachedSize(), target, stream);
  }

  // .OperationsTool.OperationReq.Quest quests = 51;
  if (_internal_has_quests()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(51, _Internal::quests(this),
        _Internal::quests(this).GetCachedSize(), target, stream);
  }

  // .OperationsTool.OperationReq.Mailbox mailbox = 61;
  if (_internal_has_mailbox()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(61, _Internal::mailbox(this),
        _Internal::mailbox(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OperationsTool.OperationReq.Property)
  return target;
}

size_t OperationReq_Property::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OperationsTool.OperationReq.Property)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (property_case()) {
    // string nickname = 1;
    case kNickname: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_nickname());
      break;
    }
    // int64 exp = 2;
    case kExp: {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_exp());
      break;
    }
    // int64 gem = 3;
    case kGem: {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_gem());
      break;
    }
    // int64 paid_gem = 4;
    case kPaidGem: {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_paid_gem());
      break;
    }
    // int64 chips = 5;
    case kChips: {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_chips());
      break;
    }
    // int64 coin = 6;
    case kCoin: {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_coin());
      break;
    }
    // int64 safe_chips = 7;
    case kSafeChips: {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_safe_chips());
      break;
    }
    // int64 safe_coin = 8;
    case kSafeCoin: {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_safe_coin());
      break;
    }
    // int64 rakeback = 9;
    case kRakeback: {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_rakeback());
      break;
    }
    // int32 kick_ticket_count = 10;
    case kKickTicketCount: {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_kick_ticket_count());
      break;
    }
    // string membership_expiry_time = 11;
    case kMembershipExpiryTime: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_membership_expiry_time());
      break;
    }
    // int64 daily_lost_chip = 21;
    case kDailyLostChip: {
      total_size += 2 +
        ::_pbi::WireFormatLite::Int64Size(
          this->_internal_daily_lost_chip());
      break;
    }
    // int64 lost_limit = 22;
    case kLostLimit: {
      total_size += 2 +
        ::_pbi::WireFormatLite::Int64Size(
          this->_internal_lost_limit());
      break;
    }
    // string refresh_time_of_loss_limit = 23;
    case kRefreshTimeOfLossLimit: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_refresh_time_of_loss_limit());
      break;
    }
    // int64 monthly_buy_total = 24;
    case kMonthlyBuyTotal: {
      total_size += 2 +
        ::_pbi::WireFormatLite::Int64Size(
          this->_internal_monthly_buy_total());
      break;
    }
    // int64 buy_limit = 25;
    case kBuyLimit: {
      total_size += 2 +
        ::_pbi::WireFormatLite::Int64Size(
          this->_internal_buy_limit());
      break;
    }
    // string refresh_time_of_buy_limit = 26;
    case kRefreshTimeOfBuyLimit: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_refresh_time_of_buy_limit());
      break;
    }
    // string reg_date = 31;
    case kRegDate: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_reg_date());
      break;
    }
    // .OperationsTool.OperationReq.Avatar avatars = 41;
    case kAvatars: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.property_.avatars_);
      break;
    }
    // .OperationsTool.OperationReq.Quest quests = 51;
    case kQuests: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.property_.quests_);
      break;
    }
    // .OperationsTool.OperationReq.Mailbox mailbox = 61;
    case kMailbox: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.property_.mailbox_);
      break;
    }
    case PROPERTY_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OperationReq_Property::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OperationReq_Property::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OperationReq_Property::GetClassData() const { return &_class_data_; }


void OperationReq_Property::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OperationReq_Property*>(&to_msg);
  auto& from = static_cast<const OperationReq_Property&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:OperationsTool.OperationReq.Property)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.property_case()) {
    case kNickname: {
      _this->_internal_set_nickname(from._internal_nickname());
      break;
    }
    case kExp: {
      _this->_internal_set_exp(from._internal_exp());
      break;
    }
    case kGem: {
      _this->_internal_set_gem(from._internal_gem());
      break;
    }
    case kPaidGem: {
      _this->_internal_set_paid_gem(from._internal_paid_gem());
      break;
    }
    case kChips: {
      _this->_internal_set_chips(from._internal_chips());
      break;
    }
    case kCoin: {
      _this->_internal_set_coin(from._internal_coin());
      break;
    }
    case kSafeChips: {
      _this->_internal_set_safe_chips(from._internal_safe_chips());
      break;
    }
    case kSafeCoin: {
      _this->_internal_set_safe_coin(from._internal_safe_coin());
      break;
    }
    case kRakeback: {
      _this->_internal_set_rakeback(from._internal_rakeback());
      break;
    }
    case kKickTicketCount: {
      _this->_internal_set_kick_ticket_count(from._internal_kick_ticket_count());
      break;
    }
    case kMembershipExpiryTime: {
      _this->_internal_set_membership_expiry_time(from._internal_membership_expiry_time());
      break;
    }
    case kDailyLostChip: {
      _this->_internal_set_daily_lost_chip(from._internal_daily_lost_chip());
      break;
    }
    case kLostLimit: {
      _this->_internal_set_lost_limit(from._internal_lost_limit());
      break;
    }
    case kRefreshTimeOfLossLimit: {
      _this->_internal_set_refresh_time_of_loss_limit(from._internal_refresh_time_of_loss_limit());
      break;
    }
    case kMonthlyBuyTotal: {
      _this->_internal_set_monthly_buy_total(from._internal_monthly_buy_total());
      break;
    }
    case kBuyLimit: {
      _this->_internal_set_buy_limit(from._internal_buy_limit());
      break;
    }
    case kRefreshTimeOfBuyLimit: {
      _this->_internal_set_refresh_time_of_buy_limit(from._internal_refresh_time_of_buy_limit());
      break;
    }
    case kRegDate: {
      _this->_internal_set_reg_date(from._internal_reg_date());
      break;
    }
    case kAvatars: {
      _this->_internal_mutable_avatars()->::OperationsTool::OperationReq_Avatar::MergeFrom(
          from._internal_avatars());
      break;
    }
    case kQuests: {
      _this->_internal_mutable_quests()->::OperationsTool::OperationReq_Quest::MergeFrom(
          from._internal_quests());
      break;
    }
    case kMailbox: {
      _this->_internal_mutable_mailbox()->::OperationsTool::OperationReq_Mailbox::MergeFrom(
          from._internal_mailbox());
      break;
    }
    case PROPERTY_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OperationReq_Property::CopyFrom(const OperationReq_Property& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OperationsTool.OperationReq.Property)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OperationReq_Property::IsInitialized() const {
  return true;
}

void OperationReq_Property::InternalSwap(OperationReq_Property* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.property_, other->_impl_.property_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata OperationReq_Property::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Operation_2eproto_getter, &descriptor_table_Operation_2eproto_once,
      file_level_metadata_Operation_2eproto[1]);
}

// ===================================================================

class OperationReq_Avatar::_Internal {
 public:
};

OperationReq_Avatar::OperationReq_Avatar(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:OperationsTool.OperationReq.Avatar)
}
OperationReq_Avatar::OperationReq_Avatar(const OperationReq_Avatar& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OperationReq_Avatar* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.expiry_date_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.expiry_date_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.expiry_date_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_expiry_date().empty()) {
    _this->_impl_.expiry_date_.Set(from._internal_expiry_date(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:OperationsTool.OperationReq.Avatar)
}

inline void OperationReq_Avatar::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.expiry_date_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.expiry_date_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.expiry_date_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

OperationReq_Avatar::~OperationReq_Avatar() {
  // @@protoc_insertion_point(destructor:OperationsTool.OperationReq.Avatar)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OperationReq_Avatar::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.expiry_date_.Destroy();
}

void OperationReq_Avatar::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OperationReq_Avatar::Clear() {
// @@protoc_insertion_point(message_clear_start:OperationsTool.OperationReq.Avatar)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.expiry_date_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OperationReq_Avatar::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string expiry_date = 41;
      case 41:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          auto str = _internal_mutable_expiry_date();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "OperationsTool.OperationReq.Avatar.expiry_date"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OperationReq_Avatar::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:OperationsTool.OperationReq.Avatar)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string expiry_date = 41;
  if (!this->_internal_expiry_date().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_expiry_date().data(), static_cast<int>(this->_internal_expiry_date().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "OperationsTool.OperationReq.Avatar.expiry_date");
    target = stream->WriteStringMaybeAliased(
        41, this->_internal_expiry_date(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OperationsTool.OperationReq.Avatar)
  return target;
}

size_t OperationReq_Avatar::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OperationsTool.OperationReq.Avatar)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string expiry_date = 41;
  if (!this->_internal_expiry_date().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_expiry_date());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OperationReq_Avatar::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OperationReq_Avatar::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OperationReq_Avatar::GetClassData() const { return &_class_data_; }


void OperationReq_Avatar::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OperationReq_Avatar*>(&to_msg);
  auto& from = static_cast<const OperationReq_Avatar&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:OperationsTool.OperationReq.Avatar)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_expiry_date().empty()) {
    _this->_internal_set_expiry_date(from._internal_expiry_date());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OperationReq_Avatar::CopyFrom(const OperationReq_Avatar& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OperationsTool.OperationReq.Avatar)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OperationReq_Avatar::IsInitialized() const {
  return true;
}

void OperationReq_Avatar::InternalSwap(OperationReq_Avatar* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.expiry_date_, lhs_arena,
      &other->_impl_.expiry_date_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata OperationReq_Avatar::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Operation_2eproto_getter, &descriptor_table_Operation_2eproto_once,
      file_level_metadata_Operation_2eproto[2]);
}

// ===================================================================

class OperationReq_Quest::_Internal {
 public:
};

OperationReq_Quest::OperationReq_Quest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:OperationsTool.OperationReq.Quest)
}
OperationReq_Quest::OperationReq_Quest(const OperationReq_Quest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OperationReq_Quest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.current_count_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.current_count_ = from._impl_.current_count_;
  // @@protoc_insertion_point(copy_constructor:OperationsTool.OperationReq.Quest)
}

inline void OperationReq_Quest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.current_count_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

OperationReq_Quest::~OperationReq_Quest() {
  // @@protoc_insertion_point(destructor:OperationsTool.OperationReq.Quest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OperationReq_Quest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void OperationReq_Quest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OperationReq_Quest::Clear() {
// @@protoc_insertion_point(message_clear_start:OperationsTool.OperationReq.Quest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.current_count_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OperationReq_Quest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 current_count = 51;
      case 51:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 152)) {
          _impl_.current_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OperationReq_Quest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:OperationsTool.OperationReq.Quest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 current_count = 51;
  if (this->_internal_current_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(51, this->_internal_current_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OperationsTool.OperationReq.Quest)
  return target;
}

size_t OperationReq_Quest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OperationsTool.OperationReq.Quest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 current_count = 51;
  if (this->_internal_current_count() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int64Size(
        this->_internal_current_count());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OperationReq_Quest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OperationReq_Quest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OperationReq_Quest::GetClassData() const { return &_class_data_; }


void OperationReq_Quest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OperationReq_Quest*>(&to_msg);
  auto& from = static_cast<const OperationReq_Quest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:OperationsTool.OperationReq.Quest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_current_count() != 0) {
    _this->_internal_set_current_count(from._internal_current_count());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OperationReq_Quest::CopyFrom(const OperationReq_Quest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OperationsTool.OperationReq.Quest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OperationReq_Quest::IsInitialized() const {
  return true;
}

void OperationReq_Quest::InternalSwap(OperationReq_Quest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.current_count_, other->_impl_.current_count_);
}

::PROTOBUF_NAMESPACE_ID::Metadata OperationReq_Quest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Operation_2eproto_getter, &descriptor_table_Operation_2eproto_once,
      file_level_metadata_Operation_2eproto[3]);
}

// ===================================================================

class OperationReq_Mailbox::_Internal {
 public:
};

OperationReq_Mailbox::OperationReq_Mailbox(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:OperationsTool.OperationReq.Mailbox)
}
OperationReq_Mailbox::OperationReq_Mailbox(const OperationReq_Mailbox& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OperationReq_Mailbox* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.mail_idx_){from._impl_.mail_idx_}
    , /*decltype(_impl_._mail_idx_cached_byte_size_)*/{0}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:OperationsTool.OperationReq.Mailbox)
}

inline void OperationReq_Mailbox::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.mail_idx_){arena}
    , /*decltype(_impl_._mail_idx_cached_byte_size_)*/{0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

OperationReq_Mailbox::~OperationReq_Mailbox() {
  // @@protoc_insertion_point(destructor:OperationsTool.OperationReq.Mailbox)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OperationReq_Mailbox::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.mail_idx_.~RepeatedField();
}

void OperationReq_Mailbox::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OperationReq_Mailbox::Clear() {
// @@protoc_insertion_point(message_clear_start:OperationsTool.OperationReq.Mailbox)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.mail_idx_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OperationReq_Mailbox::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated int64 mail_idx = 61;
      case 61:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 234)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt64Parser(_internal_mutable_mail_idx(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 232) {
          _internal_add_mail_idx(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OperationReq_Mailbox::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:OperationsTool.OperationReq.Mailbox)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int64 mail_idx = 61;
  {
    int byte_size = _impl_._mail_idx_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt64Packed(
          61, _internal_mail_idx(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OperationsTool.OperationReq.Mailbox)
  return target;
}

size_t OperationReq_Mailbox::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OperationsTool.OperationReq.Mailbox)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int64 mail_idx = 61;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int64Size(this->_impl_.mail_idx_);
    if (data_size > 0) {
      total_size += 2 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._mail_idx_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OperationReq_Mailbox::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OperationReq_Mailbox::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OperationReq_Mailbox::GetClassData() const { return &_class_data_; }


void OperationReq_Mailbox::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OperationReq_Mailbox*>(&to_msg);
  auto& from = static_cast<const OperationReq_Mailbox&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:OperationsTool.OperationReq.Mailbox)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.mail_idx_.MergeFrom(from._impl_.mail_idx_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OperationReq_Mailbox::CopyFrom(const OperationReq_Mailbox& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OperationsTool.OperationReq.Mailbox)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OperationReq_Mailbox::IsInitialized() const {
  return true;
}

void OperationReq_Mailbox::InternalSwap(OperationReq_Mailbox* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.mail_idx_.InternalSwap(&other->_impl_.mail_idx_);
}

::PROTOBUF_NAMESPACE_ID::Metadata OperationReq_Mailbox::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Operation_2eproto_getter, &descriptor_table_Operation_2eproto_once,
      file_level_metadata_Operation_2eproto[4]);
}

// ===================================================================

class OperationReq::_Internal {
 public:
  static const ::OperationsTool::OperationReq_Property& before(const OperationReq* msg);
  static const ::OperationsTool::OperationReq_Property& after(const OperationReq* msg);
};

const ::OperationsTool::OperationReq_Property&
OperationReq::_Internal::before(const OperationReq* msg) {
  return *msg->_impl_.before_;
}
const ::OperationsTool::OperationReq_Property&
OperationReq::_Internal::after(const OperationReq* msg) {
  return *msg->_impl_.after_;
}
OperationReq::OperationReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:OperationsTool.OperationReq)
}
OperationReq::OperationReq(const OperationReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OperationReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.reason_){}
    , decltype(_impl_.before_){nullptr}
    , decltype(_impl_.after_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.reason_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.reason_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_reason().empty()) {
    _this->_impl_.reason_.Set(from._internal_reason(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_before()) {
    _this->_impl_.before_ = new ::OperationsTool::OperationReq_Property(*from._impl_.before_);
  }
  if (from._internal_has_after()) {
    _this->_impl_.after_ = new ::OperationsTool::OperationReq_Property(*from._impl_.after_);
  }
  // @@protoc_insertion_point(copy_constructor:OperationsTool.OperationReq)
}

inline void OperationReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.reason_){}
    , decltype(_impl_.before_){nullptr}
    , decltype(_impl_.after_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.reason_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.reason_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

OperationReq::~OperationReq() {
  // @@protoc_insertion_point(destructor:OperationsTool.OperationReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OperationReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.reason_.Destroy();
  if (this != internal_default_instance()) delete _impl_.before_;
  if (this != internal_default_instance()) delete _impl_.after_;
}

void OperationReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OperationReq::Clear() {
// @@protoc_insertion_point(message_clear_start:OperationsTool.OperationReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.reason_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.before_ != nullptr) {
    delete _impl_.before_;
  }
  _impl_.before_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.after_ != nullptr) {
    delete _impl_.after_;
  }
  _impl_.after_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OperationReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .OperationsTool.OperationReq.Property before = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_before(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .OperationsTool.OperationReq.Property after = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_after(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string reason = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_reason();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "OperationsTool.OperationReq.reason"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OperationReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:OperationsTool.OperationReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .OperationsTool.OperationReq.Property before = 1;
  if (this->_internal_has_before()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::before(this),
        _Internal::before(this).GetCachedSize(), target, stream);
  }

  // .OperationsTool.OperationReq.Property after = 2;
  if (this->_internal_has_after()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::after(this),
        _Internal::after(this).GetCachedSize(), target, stream);
  }

  // string reason = 3;
  if (!this->_internal_reason().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_reason().data(), static_cast<int>(this->_internal_reason().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "OperationsTool.OperationReq.reason");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_reason(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OperationsTool.OperationReq)
  return target;
}

size_t OperationReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OperationsTool.OperationReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string reason = 3;
  if (!this->_internal_reason().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_reason());
  }

  // .OperationsTool.OperationReq.Property before = 1;
  if (this->_internal_has_before()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.before_);
  }

  // .OperationsTool.OperationReq.Property after = 2;
  if (this->_internal_has_after()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.after_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OperationReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OperationReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OperationReq::GetClassData() const { return &_class_data_; }


void OperationReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OperationReq*>(&to_msg);
  auto& from = static_cast<const OperationReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:OperationsTool.OperationReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_reason().empty()) {
    _this->_internal_set_reason(from._internal_reason());
  }
  if (from._internal_has_before()) {
    _this->_internal_mutable_before()->::OperationsTool::OperationReq_Property::MergeFrom(
        from._internal_before());
  }
  if (from._internal_has_after()) {
    _this->_internal_mutable_after()->::OperationsTool::OperationReq_Property::MergeFrom(
        from._internal_after());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OperationReq::CopyFrom(const OperationReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OperationsTool.OperationReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OperationReq::IsInitialized() const {
  return true;
}

void OperationReq::InternalSwap(OperationReq* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.reason_, lhs_arena,
      &other->_impl_.reason_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OperationReq, _impl_.after_)
      + sizeof(OperationReq::_impl_.after_)
      - PROTOBUF_FIELD_OFFSET(OperationReq, _impl_.before_)>(
          reinterpret_cast<char*>(&_impl_.before_),
          reinterpret_cast<char*>(&other->_impl_.before_));
}

::PROTOBUF_NAMESPACE_ID::Metadata OperationReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Operation_2eproto_getter, &descriptor_table_Operation_2eproto_once,
      file_level_metadata_Operation_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace OperationsTool
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::OperationsTool::Claim*
Arena::CreateMaybeMessage< ::OperationsTool::Claim >(Arena* arena) {
  return Arena::CreateMessageInternal< ::OperationsTool::Claim >(arena);
}
template<> PROTOBUF_NOINLINE ::OperationsTool::OperationReq_Property*
Arena::CreateMaybeMessage< ::OperationsTool::OperationReq_Property >(Arena* arena) {
  return Arena::CreateMessageInternal< ::OperationsTool::OperationReq_Property >(arena);
}
template<> PROTOBUF_NOINLINE ::OperationsTool::OperationReq_Avatar*
Arena::CreateMaybeMessage< ::OperationsTool::OperationReq_Avatar >(Arena* arena) {
  return Arena::CreateMessageInternal< ::OperationsTool::OperationReq_Avatar >(arena);
}
template<> PROTOBUF_NOINLINE ::OperationsTool::OperationReq_Quest*
Arena::CreateMaybeMessage< ::OperationsTool::OperationReq_Quest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::OperationsTool::OperationReq_Quest >(arena);
}
template<> PROTOBUF_NOINLINE ::OperationsTool::OperationReq_Mailbox*
Arena::CreateMaybeMessage< ::OperationsTool::OperationReq_Mailbox >(Arena* arena) {
  return Arena::CreateMessageInternal< ::OperationsTool::OperationReq_Mailbox >(arena);
}
template<> PROTOBUF_NOINLINE ::OperationsTool::OperationReq*
Arena::CreateMaybeMessage< ::OperationsTool::OperationReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::OperationsTool::OperationReq >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
