#pragma once

namespace protoutil
{
	enum E_PROTO_STRING_ERROR_CODE
	{
		E_PROTO_STRING_ERROR_CODE_OK,
		E_PROTO_STRING_ERROR_CODE_DESCRIPTORPOOL,
		E_PROTO_STRING_ERROR_CODE_DESCRIPTOR,
		E_PROTO_STRING_ERROR_CODE_PROTOTYPE,
		E_PROTO_STRING_ERROR_CODE_MESSAGE,
		E_PROTO_STRING_ERROR_CODE_UTF8_CONVERT,
		E_PROTO_STRING_ERROR_CODE_MAX,
	};

	enum E_PROTO_UTIL_BUFFER
	{
		MIN_ACCOUNT_NICKNAME_LEN_W = 4,
		MAX_ACCOUNT_NICKNAME_LEN_W = 16,
		MIN_ACCOUNT_NICKNAME_LEN_A = MIN_ACCOUNT_NICKNAME_LEN_W * 2,
		MAX_ACCOUNT_NICKNAME_LEN_A = MAX_ACCOUNT_NICKNAME_LEN_W * 2,
		MIN_ACCOUNT_NICKNAME_LEN_UTF8 = MIN_ACCOUNT_NICKNAME_LEN_W * 3,
		MAX_ACCOUNT_NICKNAME_LEN_UTF8 = MAX_ACCOUNT_NICKNAME_LEN_W * 3,

		MAX_BUFFER_64_LEN	=	64,
		MAX_BUFFER_128_LEN	=	128,
		MAX_BUFFER_2K_LEN	=	1024 * 2,
		MAX_BUFFER_32K_LEN	=	1204 * 32,
		MAX_BUFFER_64K_LEN	=	1024 * 64,	// 프로토 버퍼에서 쓸 데이터, 시리얼 라이즈용 버퍼 사이즈 65536
	};
};

enum class e_thread_type
{
	e_command_thread,
	e_web_thread,
	e_udp_thread
};