#pragma once
#include "TableServerHeader.h"


//#include "message.pb.h" // Generated by Protobuf compiler
#include <iostream>
#include <cpp_redis>

#include "../../ProtocolBuffer/cpp/General.pb.h"
#include "../../ProtocolBuffer/cpp/PmNet.pb.h"

enum class eRedisChannelUse;

class cRedisController
{
private:
	static eRedisChannelUse GetRedisBattleChannelUse();

public:

	//void RankTest(eRedisChannelUse channel);


//NICE인증 내역
	void GetAuthData( const std::string& requestNo , std::string& out );
	void DeleteAuthData( const std::string& requestNo);


	/*void SetPlayerPinball( const uint64& playerIdx , const Common::PinballType& _pinball_type, const PmNet::ReplayMarbleRS& res );
	BOOL GetPlayerPinball( const uint64& playerIdx , const Common::PinballType& _pinball_type, PmNet::ReplayMarbleRS& res );
	BOOL DeletePlayerPinball( const uint64_t& playerIdx, const Common::PinballType& _pinball_type );
	void DeletePlayerPinballAsync( const uint64_t& playerIdx , const Common::PinballType& _pinball_type, std::function<void( bool )> callback );*/
public:
	cRedisController();
	~cRedisController();
};

